generate_route:
  path: /product/generate
  defaults: {_controller: 'App\Controller\ProductController::generate'}
  methods:  [GET]
index_route:
  path: /product
  defaults: {_controller: 'App\Controller\ProductController::index'}
  methods:  [GET]
create_order_route:
  path: /order
  defaults: {_controller: 'App\Controller\OrderController::create'}
  methods:  [POST]
charge_order_route:
  path: /order/charge
  defaults: {_controller: 'App\Controller\OrderController::charge'}
  methods:  [PUT]
